---
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    reviewers:
      - oltionzefi
    assignees:
      - oltionzefi
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
